apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-deployment
  labels:
    app: rust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-pod
  template:
    metadata:
      labels:
        app: rust-pod
    spec:
      containers:
      - name: rust-container
        image: ratulb/rust-debian
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: rust-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 50051
    protocol: TCP
    name: http
  selector:
    app: rust-pod
---
